language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
before_install:
  - yes | gem update --system --force
  - gem install bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle install — jobs=3 — retry=3
  - bundle exec rake db:migrate
  - bundle exec rspec
